### ISSUE TITLE
这个前端页面是基于vue的吗，也需要docker吗，我没安装这两个，怎么破

### ISSUE THREAD

**Issue by golang730** [hantmac/fuckdb#14]

**Comment by golang730** [comment]
我是win10环境

**Comment by hantmac** [comment]
如果是源码部署的话，cd frontend 然后 npm install && npm start 前端就可以了；
后端直接 go run main.go 就行

**Comment by hantmac** [comment]
win 10 也可以直接下载可执行文件，用命令行操作
https://github.com/hantmac/fuckdb/releases/download/v0.3/fuckdb_win.tar.gz

**Comment by golang730** [comment]
好的，谢谢，看了好多，就你这个项目最好，

**Comment by hantmac** [comment]
@Dante666999 有什么问题随时提出 😄

**Comment by Dante666999** [comment]
npm install && npm start
这样前端可以访问了，但是，请求的后台地址是0.0.0.0这是咋回事啊，在那改啊，
