### ISSUE TITLE
解决了 谢谢

### ISSUE THREAD

**Issue by GrumpyOmer** [hantmac/fuckdb#17]

**Comment by GrumpyOmer** [comment]
还有我的数据库在容器里呢 目前只能通过容器内访问宿主机再由宿主机映射到db对应的容器里面去 感觉有点怪怪的

**Comment by GrumpyOmer** [comment]
是我自己看错了,😂

**Comment by hantmac** [comment]
没关系，有问题随时提出 😄 。
ps : 如果是 macOS 的话，可以直接 `brew tap hantmac/tap && brew install fuckdb` 安装 命令行，感觉命令行很好用。
![image](https://user-images.githubusercontent.com/7600925/85521871-77f19900-b637-11ea-8774-d5572fd294ca.png)
