### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by gzq-myy** [hantmac/fuckdb#21]
linux安装fuckdb Lite
使用这个命令吗
![image](https://user-images.githubusercontent.com/34859258/90972283-48cdaa00-e54a-11ea-8bc2-84752641df26.png)
执行完以后的结果
![image](https://user-images.githubusercontent.com/34859258/91003251-5f840780-e603-11ea-8f8c-1d15390f37cf.png)

使用fuckdb Lite是否是在fuckdb的基础上，要先安装fuckdb才能使用fuckdb Lite吗，文档让人有点疑惑

**Comment by hantmac** [comment]
@GaoHaHa-IronMan  1. wget https://github.com/hantmac/fuckdb/releases/download/v0.3/fuckdb_linux.tar.gz 用这个下载，下载后 tar -zxvf fuckdb_linux.tar.gz 就拿到可执行文件了

2. fuckdb lite 是单独使用的，跟 fuckdb 没有任何关系，我修改下文档，感谢指出 😄
