### ISSUE TITLE
生成结构体时连不上本地数据库

### ISSUE THREAD

**Issue by gxdgxd** [hantmac/fuckdb#44]
数据库信息都正确，但Create时，调用http://0.0.0.0:8000/api/db2struct接口返回error: "dial tcp 127.0.0.1:3306: connect: connection refused"

**Comment by chenqinghe** [comment]
@gxdgxd 下拉列表中是否可以列出数据库中的表？ 如果不行的话，检查一下数据库是否启动，端口是否正确，密码是否正确。

**Comment by hantmac** [comment]
![image](https://user-images.githubusercontent.com/7600925/123359363-8ef6fe00-d59f-11eb-8e5c-7cf524412ffd.png)

看下这个能拉下来么

**Comment by hantmac** [comment]
@chenqinghe 可以考虑加一个 TestConnection 的按钮

**Comment by chenqinghe** [comment]
@hantmac  可以的，页面上是有的，功能还没实现……

**Comment by gxdgxd** [comment]
> ![image](https://user-images.githubusercontent.com/7600925/123359363-8ef6fe00-d59f-11eb-8e5c-7cf524412ffd.png)
> 
> 看下这个能拉下来么



> ![image](https://user-images.githubusercontent.com/7600925/123359363-8ef6fe00-d59f-11eb-8e5c-7cf524412ffd.png)
> 
> 看下这个能拉下来么

你好，我使用的版本怎么和你用的不一样，我的页面是这样的，我确定数据库启动了，账号密码都正确但是连不上数据库
![image](https://user-images.githubusercontent.com/25735759/123436567-57b93900-d601-11eb-8ebf-119df9672681.png)

**Comment by hantmac** [comment]
@gxdgxd 用最新的 1.01 版本，https://github.com/hantmac/fuckdb/releases/tag/v1.0.1

**Comment by gxdgxd** [comment]
@hantmac 我在idea里面切换的就是1.01版本，但是也没还是没变，和你的不一样，求指导？
我的操作步骤是：1.切换到1.01版本；2.docker-compose up -d启动容器；3.访问http://localhost:8000/#/，页面就是我发的那张图

**Comment by hantmac** [comment]
> @hantmac 我在idea里面切换的就是1.01版本，但是也没还是没变，和你的不一样，求指导？
> 我的操作步骤是：1.切换到1.01版本；2.docker-compose up -d启动容器；3.访问[http://localhost:8000/#/，页面就是我发的那张图](http://localhost:8000/#/%EF%BC%8C%E9%A1%B5%E9%9D%A2%E5%B0%B1%E6%98%AF%E6%88%91%E5%8F%91%E7%9A%84%E9%82%A3%E5%BC%A0%E5%9B%BE)

你用 docker-compose 起的呀，这个会有网络问题，建议用 cmd 模式
