### ISSUE TITLE
error formatting: 23:9: string literal not terminated (and 1 more errors), was formatting package 

### ISSUE THREAD

**Issue by hantmac** [hantmac/fuckdb#45]
error formatting: 23:9: string literal not terminated (and 1 more errors), was formatting package

**Comment by chenqinghe** [comment]
可能是模板有问题，生成代码后format失败了

**Comment by hantmac** [comment]
> 可能是模板有问题，生成代码后format失败了

是的，定位到这里了，`formatted, err := format.Source(buf.Bytes())`
