### ISSUE TITLE
json驼峰

### ISSUE THREAD

**Issue by once10301** [hantmac/fuckdb#47]
fuckdb generate生成的fuckdb.json可以加个开关使生成的json不是下划线而是小驼峰吗

**Comment by hantmac** [comment]
```go
type A struct {
CreatedBy string    `json:"createdBy"`
}
```

是这种类型吗

**Comment by once10301** [comment]
是的，Flutter那边希望是小驼峰的格式
@JSONField(name: "mobile_phone")
String mobilePhone;

**Comment by once10301** [comment]
请问有进展吗？

**Comment by hantmac** [comment]
> 请问有进展吗？

最近有点忙，还没来得看😹

**Comment by once10301** [comment]
还有就是能不能根据MySQL里面的顺序排序呢

**Comment by hantmac** [comment]
> 还有就是能不能根据MySQL里面的顺序排序呢

按顺序可能不太好做

**Comment by yann0917** [comment]
> 还有就是能不能根据MySQL里面的顺序排序呢

可以用我 fork 的版本，是根据 MySQL 顺序排序的。[地址](https://github.com/yann0917/fuckdb)

![image](https://user-images.githubusercontent.com/25262709/130001382-b0d49938-5a83-4468-ab06-493d7cb0bee4.png)

**Comment by hantmac** [comment]
@yann0917 能否提个 PR 合并到主分支呀

**Comment by yann0917** [comment]
> @yann0917 能否提个 PR 合并到主分支呀

🤣 不行啊，分支差异太大了，很多冲突。

**Comment by hantmac** [comment]
> > @yann0917 能否提个 PR 合并到主分支呀
> 
> 🤣 不行啊，分支差异太大了，很多冲突。

回头我研究下你代码，抄过来 🐶
